// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_configuration_catalog_type_id_ from "./routes/[[configuration]]/catalog/[type]/[id].tsx";
import * as $_configuration_catalog_movie_movieCatalog_json from "./routes/[[configuration]]/catalog/movie/movieCatalog.json.ts";
import * as $_configuration_catalog_movie_movieCatalog_genre_q_json from "./routes/[[configuration]]/catalog/movie/movieCatalog/genre=[q].json.ts";
import * as $_configuration_catalog_movie_movieCatalog_search_q_json from "./routes/[[configuration]]/catalog/movie/movieCatalog/search=[q].json.ts";
import * as $_configuration_catalog_movie_movieCatalog_skip_n_json from "./routes/[[configuration]]/catalog/movie/movieCatalog/skip=[n].json.ts";
import * as $_configuration_catalog_series_seriesCatalog_json from "./routes/[[configuration]]/catalog/series/seriesCatalog.json.ts";
import * as $_configuration_manifest_json from "./routes/[[configuration]]/manifest.json.ts";
import * as $_configuration_stream_type_id_ from "./routes/[[configuration]]/stream/[type]/[id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $account_index from "./routes/account/index.tsx";
import * as $account_login from "./routes/account/login.tsx";
import * as $account_logout from "./routes/account/logout.tsx";
import * as $account_register from "./routes/account/register.tsx";
import * as $configure_index from "./routes/configure/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $Catalog from "./islands/Catalog.tsx";
import * as $Catalogs from "./islands/Catalogs.tsx";
import * as $Configurator from "./islands/Configurator.tsx";
import * as $Meta from "./islands/Meta.tsx";
import * as $Nav from "./islands/Nav.tsx";
import * as $Navigator from "./islands/Navigator.tsx";
import * as $Streams from "./islands/Streams.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[[configuration]]/catalog/[type]/[id].tsx":
      $_configuration_catalog_type_id_,
    "./routes/[[configuration]]/catalog/movie/movieCatalog.json.ts":
      $_configuration_catalog_movie_movieCatalog_json,
    "./routes/[[configuration]]/catalog/movie/movieCatalog/genre=[q].json.ts":
      $_configuration_catalog_movie_movieCatalog_genre_q_json,
    "./routes/[[configuration]]/catalog/movie/movieCatalog/search=[q].json.ts":
      $_configuration_catalog_movie_movieCatalog_search_q_json,
    "./routes/[[configuration]]/catalog/movie/movieCatalog/skip=[n].json.ts":
      $_configuration_catalog_movie_movieCatalog_skip_n_json,
    "./routes/[[configuration]]/catalog/series/seriesCatalog.json.ts":
      $_configuration_catalog_series_seriesCatalog_json,
    "./routes/[[configuration]]/manifest.json.ts":
      $_configuration_manifest_json,
    "./routes/[[configuration]]/stream/[type]/[id].tsx":
      $_configuration_stream_type_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/account/index.tsx": $account_index,
    "./routes/account/login.tsx": $account_login,
    "./routes/account/logout.tsx": $account_logout,
    "./routes/account/register.tsx": $account_register,
    "./routes/configure/index.tsx": $configure_index,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Catalog.tsx": $Catalog,
    "./islands/Catalogs.tsx": $Catalogs,
    "./islands/Configurator.tsx": $Configurator,
    "./islands/Meta.tsx": $Meta,
    "./islands/Nav.tsx": $Nav,
    "./islands/Navigator.tsx": $Navigator,
    "./islands/Streams.tsx": $Streams,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
